### ISSUE TITLE
Publish v0.1.0 to npm

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#10]
We could have a strategy here to implements parts of the api and release it in chunks, or we implement everything first and then release 1.0.0. Personally I vote to implement a subset of the api and release that before implementing less important functions.

**Comment by Jikstra** [comment]
> Personally I vote to implement a subset of the api and release that before implementing less important functions.

Yes. Maybe we should write a small reference client so that we see which methods are needed. And as soon as we can create/list chats, add contacts, send & retrieve messages, i think we are fine to make a 0.0.1 release.

**Comment by ralphtheninja** [comment]
> Yes. Maybe we should write a small reference client so that we see which methods are needed. And as soon as we can create/list chats, add contacts, send & retrieve messages, i think we are fine to make a 0.0.1 release.

Agreed! Up for writing a cli client? :)

**Comment by ralphtheninja** [comment]
I personally like the style of https://github.com/cabal-club/cabal (using `neat-log` for cli ui)
