### ISSUE TITLE
Rewrite open/configure logic

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#104]
Currently, we set `opts` in the constructor which does two things:

* stores `opts` on `this.opts` for later usage
* creates `this.dcn_context` by calling `binding.dcn_context_new()`

Later on we do `dc.open(cb)` which does two things:

* opens the database
* configures the context if it's not yet configured

This setup is a bit problematic since `.open()` does too much and affects applications like `deltachat-desktop` which has to provide login details (`addr` and `mail_pw`) _each_ time the context is created ( via the constructor), which prevents behavior as just starting the app if it's already configured.

I propose the following:

* remove `opts` from the constructor, which should _only_ create the context
* `.open()` should _only_ open the underlying database and callback when done
* move out configuration logic from `.open()` into a separate method, which should take an `opts` object with required `addr` and `mail_pw` properties

This means an application can:

* create a context directly at startup
* check if configured, and if not, show a login screen
* if configured, skip login screen and go directly to main chatlist

Let me know what you think.

cc @karissa @r10s @Jikstra

**Comment by Jikstra** [comment]
Looks good to me :+1:

**Comment by ralphtheninja** [comment]
> Looks good to me +1

Woah, that was quick! :smile:

**Comment by Jikstra** [comment]
> Woah, that was quick! smile

Same :D

**Comment by karissa** [comment]
sounds good

**Comment by r10s** [comment]
> - remove opts from the constructor, which should only create the context
> - .open() should only open the underlying database and callback when done

this makes sense.

> - move out configuration logic from .open() into a separate method, which should take an opts object with required addr and mail_pw properties

this also makes sense.

however, i am wondering if it makes a big difference for the UI to call ...
```
dc.setAllConfig({
  addr: credentials.email,
  mail_pw: credentials.password,
  mail_server: credentials.imap_server,
  mail_user: credentials.imap_user,
  mail_port: credentials.imap_port,
  send_server: credentials.smtp_server,
  send_user: credentials.smtp_user,
  send_port: credentials.smtp_port,
  send_pw: credentials.smtp_password,
});
```
... instead of just ...
```
dc.setConfig('addr: credentials.email);
dc.setConfig('mail_pw: credentials.password);
dc.setConfig('mail_server: credentials.imap_server);
dc.setConfig('mail_user: credentials.imap_user);
dc.setConfig('mail_port: credentials.imap_port);
dc.setConfig('send_server: credentials.smtp_server);
dc.setConfig('send_user: credentials.smtp_user);
dc.setConfig('send_port: credentials.smtp_port);
dc.setConfig('send_pw: credentials.smtp_password);
```
which would save an additional wrapper that has to be maintained.

otoh an extra method may have its advantages, maybe the UI can use the opts object some where else etc.

so, i would be fine with any solution :)

**Comment by Jikstra** [comment]
> which would save an additional wrapper that has to be maintained.

Implementing both should be easy and not a big maintaining issue, as it just loops over the object key/values and calls dc.setConfig. I don't think we have to care about this being to hard to maintain for now.

**Comment by r10s** [comment]
> Implementing both should be easy and not a big maintaining issue, as it just loops over the object key/values and calls dc.setConfig. I don't think we have to care about this being to hard to maintain for now.

i see, a loop is a perfect solution :)
was only afraid of having two lists of credentials to maintain.

> I think this is more a style issue. It's more javascripty to pass an object. Also, addr and mail_pw must be set and easier to control with one method.

i'm 100% convinced :)
