### ISSUE TITLE
Make dc.initiateKeyTransfer() async

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#107]
See https://github.com/deltachat/deltachat-desktop/issues/33 for details

**Comment by ralphtheninja** [comment]
cc @Jikstra

**Comment by Jikstra** [comment]
ack, if this has time till end of next week (23.09.18 european date format ^^) i would like to do something like this to get my head wrapped around the bindings stuff again. If this has priority or blocks anyone from working on something, please just implement it, i will find other methods to turn async which will do the same for me.
Getting excited to be able to work on this in a short time again!

**Comment by ralphtheninja** [comment]
>  If this has priority or blocks anyone from working on something

It's not blocking anything, other than the javascript event loop ;)

**Comment by Jikstra** [comment]
> It's not blocking anything, other than the javascript event loop ;)

Good one :D

**Comment by ralphtheninja** [comment]
I split this one in two, see https://github.com/deltachat/deltachat-node/issues/124
