### ISSUE TITLE
Aproach for producing javascript api conform errror messages

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#109]
The problem is, that the c api for initiate_key_transfer returns null if an error happend (it could be any error, no more info for this, maybe some error event gets fired). The javascript api approach would be to have cb(err, statusCode), where err is null if no error happend. The question is, do we want to mimic this api stuff already in the lower level bindings? There is one place in the code where we produce a specific err_str, which is in my opinion an interpreted error message.
I prefer the approach of keeping the low level c bindings stuff as deltachat-core api like as possible, only introducint threading stuff and everything else which isn't possible on the higher level js.

**Comment by ralphtheninja** [comment]
@Jikstra I guess we took care of this on the last a/v? :)
