### ISSUE TITLE
How to handle DC_EVENT_HTTP_GET?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#113]
The best way would be to handle it in js land but it's problematic now since we can't use the `napi_call_threadsafe_function()` atm in electron.

I propose we pull in a simple http client on the c side and handle it directly in the switch case:

https://github.com/deltachat/deltachat-node/blob/master/src/module.c#L45-L66

cc @hpk42 @r10s @Jikstra @karissa

**Comment by ralphtheninja** [comment]
Another option would be to hang in the event handler on the c side, e.g. when `DC_EVENT_HTTP_GET` shows up and wait for something. Like:

1. if `DC_EVENT_HTTP_GET`, put event into queue and wait
2. when js gets to this event by polling the queue, it can make the http request, once done it calls back into the bindings e.g. `dc.dcn_event_http_get_response(req.body)`, which in turn can store the response on the context and trigger a signal
3. the event handler in 1. stops hanging, reads the result from the context and returns it
* the

**Comment by r10s** [comment]
> [1] I propose we pull in a simple http client on the c side and handle it directly in the switch case

this sounds rather straight-forward. however, it may get complicated when it comes to http**s**. not sure if there is a higher-level-library or code snippet that we can use here. for plain-http it would be probably sth. as https://stackoverflow.com/questions/24321295/how-can-i-download-a-file-using-c-socket-programming
using other things than sockets may, again, add new dependencies ... @flub do you have an idea what can be used there?

> [2] Another option would be to hang in the event handler on the c side, e.g. when DC_EVENT_HTTP_GET shows up and wait for something.

although this "wait" has the risk of creating suspicious deadlocks it would make the c-part easier.
also, it would only be a temporary solution as napi_call_threadsafe_function() will be there at a given time :)

not sure, i think the decision is easier if we know how many additional overhead [1] would create ...

**Comment by flub** [comment]
deltachat-core is already dealing with SSL/TSL thanks to the IMAP and SMTP functions, so HTTPS won't make things much worse I guess.  Not that I don't expect some extra fiddling.

I'm sure there's a reasonable library with just our existing dependencies (probably zlib & openssl).  But I think an important question is how is the C code going to integrate this?  It is a blocking operation and deltachat-core does not create any threads by current design.

**Comment by flub** [comment]
deltachat-core is already dealing with SSL/TSL thanks to the IMAP and SMTP functions, so HTTPS won't make things much worse I guess.  Not that I don't expect some extra fiddling.

I'm sure there's a reasonable library with just our existing dependencies (probably zlib & openssl).  But I think an important question is how is the C code going to integrate this?  It is a blocking operation and deltachat-core does not create any threads by current design.

**Comment by ralphtheninja** [comment]
> But I think an important question is how is the C code going to integrate this? It is a blocking operation and deltachat-core does not create any threads by current design.

It would be part of the node bindings c code, which does have threads, so that's cool I think.

@r10s I think I prefer the second solution, despite the deadlock thingie.

**Comment by hpk42** [comment]
On Tue, Sep 18, 2018 at 07:49 -0700, Floris Bruynooghe wrote:
> deltachat-core is already dealing with SSL/TSL thanks to the IMAP and SMTP functions, so HTTPS won't make things much worse I guess.  Not that I don't expect some extra fiddling.
> 
> I'm sure there's a reasonable library with just our existing dependencies (probably zlib & openssl).  But I think an important question is how is the C code going to integrate this?  It is a blocking operation and deltachat-core does not create any threads by current design.

that's not a big issue i think.  dc_event_http_get happens during configuration
and does not need async; in fact currently delta-core blocks waiting on the return
of the http-get.  So for now, and if there a simple enough http/s GET approach in C, 
we could use it blockingly from the node bindings (py bindings can easily call python from c, 
so no issue there). 

If later on core wants to get something from its caller in an async way ... 
we need to define an API/approach for this anyway.  Maybe something like
two queues for providing "requests" and "replies" respectively.  Or maybe
by injecting an event into delta-core ... don't know.  But once we have 
some solution we might route the http-get through this async system (which doesn't
exist yet) and forget about the http/c-library in the node bindings.

**Comment by r10s** [comment]
>  It is a blocking operation and deltachat-core does not create any threads by current design.

as @hpk42 said, delta-core waits, no need to be async here. just wanted to note that, nevertheless, DC_EVENT_HTTP_GET is called from within a thread that is created by the user of deltachat-core (the thread that calls dc_perform_imap_jobs() then)

**Comment by r10s** [comment]
@ralphtheninja thinking it over, i also think the second solution is easier. theoretically, only a few lines of code :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja thinking it over, i also think the second solution is easier. theoretically, only a few lines of code :)

Think you could do some stubbing on the c side?

**Comment by ralphtheninja** [comment]
@r10s I could get started on a branch and maybe you could help me fill out the gaps later.

**Comment by karissa** [comment]
yes, having a function on the C side to call when the http response is done makes sense.

**Comment by ralphtheninja** [comment]
@r10s I assume that the http request should follow redirects. But what if the response results in non 2xx? Would it be ok to set an empty string in this case?

**Comment by hpk42** [comment]
On Tue, Sep 18, 2018 at 10:02 -0700, Lars-Magnus Skog wrote:
> @r10s I assume that the http request should follow redirects. But what if the response results in non 2xx? Would it be ok to set an empty string in this case?

you can either return a proper string if you manage to get a 2xx (after redirects) 
or NULL.  pretty sure also an empty string is fine.
