### ISSUE TITLE
Document api in readme

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#13]

**Comment by Jikstra** [comment]
Do we want to manually document the api or use something like jsdoc?

**Comment by ralphtheninja** [comment]
Personally I prefer to have the documentation in the README, but just out of habit. So I normally write it manually. If we should generate something I vote for `doxygen` which is used by `deltachat-core`.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-node/commit/17dc9a71d97fa5307f2d6f2302ca30818f00fe28
