### ISSUE TITLE
node-gyp looks for libetpan.a which isn't there if a libetpan is there as a system library

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#132]
node-gyp fails if libetpan is installed as a system dependency as described in the build instructions of deltachat-core. The problem seems to be that meson/ninja use the system lib instead of linking to the shipped libetpan version and therefore the builddir/libetpan folder is nonexistant.
```
$ npm run rebuild

> deltachat-node@0.15.0 rebuild /home/kerle/Workspace/deltachat-node-jikstra
> node-gyp rebuild

make: Verzeichnis „/home/kerle/Workspace/deltachat-node-jikstra/build“ wird betreten
  CC(target) Release/obj.target/deltachat/src/module.o
  CC(target) Release/obj.target/deltachat/src/eventqueue.o
  SOLINK_MODULE(target) Release/obj.target/deltachat.node
g++: Fehler: ../deltachat-core/builddir/libs/libetpan/libetpan.a: Datei oder Verzeichnis nicht gefunden
make: *** [deltachat.target.mk:142: Release/obj.target/deltachat.node] Fehler 1
make: Verzeichnis „/home/kerle/Workspace/deltachat-node-jikstra/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.18.6-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kerle/Workspace/deltachat-node-jikstra
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.15.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.15.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kerle/.npm/_logs/2018-09-23T16_46_31_446Z-debug.log
```

Meson also finds libetpan-config binary, so that should be fine?

**Comment by ralphtheninja** [comment]
This shouldn't happen. Which commit of `deltachat-node` is this? Did you update submodules?

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-node/blob/master/scripts/rebuild-all.js#L20 should always pick bundled code before system

**Comment by Jikstra** [comment]
>  This shouldn't happen. Which commit of deltachat-node is this? Did you update submodules?

Latest, updaged submodule, even tried a complete new clone of deltachat-node master. It's reproducible even with fallback flag. Maybe a deltachat-core issue.

**Comment by ralphtheninja** [comment]
> Maybe a deltachat-core issue.

Aye. Uninstall system headers for now I guess :) Make an issue on deltachat-core and link to this.

**Comment by ralphtheninja** [comment]
cc @flub Not sure if this is useful information for you or not.

**Comment by karissa** [comment]
Here is a writeup I wrote for desktop: https://github.com/deltachat/deltachat-desktop#troubleshooting

**Comment by flub** [comment]
oh my, i think the etpan dep doesn't respect the forcefallback flag.  So if your etpan is new enough it would use it - not sure if that was exactly your case, but likely.  Thanks for the heads up @ralphtheninja!

**Comment by ralphtheninja** [comment]
*grumbles* I'm a bit stumped on how we should solve this. We shouldn't require people to uninstall libraries from their computer in order to compile this.

**Comment by ralphtheninja** [comment]
Currently the libraries we link to in the node bindings looks like:

https://github.com/deltachat/deltachat-node/blob/fca4ebce57391425ad7be68eaa9f01d4343ad82a/binding.gyp#L8-L16

**Comment by ralphtheninja** [comment]
@steils I think because of problems on mac. Not sure anymore since we've changed this so many times :) But I can check it out today.

**Comment by ralphtheninja** [comment]
But mac sort of doesn't work anyway due to ssl problems, maybe we can kill two birds in one stone.

**Comment by ralphtheninja** [comment]
It's not only a problem on mac, it's actually a pain on Travis even for linux. It's an old Ubuntu 14-something and I assume it's an older version of libetpan.

When linking with `-letpan` (instead of the compiled `libetpan.a` file) I get the following error:

```
/home/travis/.nvm/versions/node/v8.12.0/bin/node: symbol lookup error: 
/home/travis/build/deltachat/deltachat-node/build/Release/deltachat.node: 
undefined symbol: mailimap_set_timeout
```

I don't have this type of problem on my local machine (Ubuntu 18.10) so I think it's related to Travis. Right now I don't have the energy to fight more with Travis. I'd rather have a build server of our own.
