### ISSUE TITLE
Setup AppVeyor

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#136]
We can only do this once we know core builds well on windows.

**Comment by ralphtheninja** [comment]
We might want to consider using travis for windows instead.

**Comment by homdx** [comment]
Builded binary deltachat-core need testing:
[deltachat/deltachat-core#306 (comment)](https://github.com/deltachat/deltachat-core/issues/306#issuecomment-461026117)
Possible problems: Windows does not support utf-8 coding, windows uses ansi encoding. (need fix).

**Comment by homdx** [comment]
You can build with my instruction, under Windows:
https://github.com/deltachat/deltachat-desktop/issues/606#issuecomment-465064978
