### ISSUE TITLE
propagate DC_EVENT_CONFIGURE_PROGRESS events

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-node#138]

**Comment by karissa** [comment]
was able to get around this by looking at 'ALL' events and then finding `2041`

**Comment by ralphtheninja** [comment]
It's called here https://github.com/deltachat/deltachat-node/blob/master/index.js#L638-L640

**Comment by ralphtheninja** [comment]
@karissa Are you sure this doesn't work? It works with no problem on my machine.

```js
dc.on('DC_EVENT_CONFIGURE_PROGRESS', data1 => {
  log('DC_EVENT_CONFIGURE_PROGRESS', data1)    
  if (Number(data1) === 0) { // login failed   
    log('logging out')                         
    self.logout()                              
  }                                            
})                                             
```

**Comment by karissa** [comment]
yeah for some reason I wasn't able to get it to work yesterday, *shrug* perhaps there was another confounding issue..

**Comment by ralphtheninja** [comment]
Maybe the upper line here was blocking

https://github.com/deltachat/deltachat-node/blob/a1f9d57a5dd81f766501bb50fd22628f38536b96/index.js#L639-L640

We could switch these lines
