### ISSUE TITLE
Properly test initiate/continue key transfer

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#142]
Currently we have a integration test which gets skipped because i need to figure out the msgId on second connection for the key exchange. Listening for DC_EVENT_INCOMING_MSG should be enough in my opinion but i don't receive any event. See https://github.com/deltachat/deltachat-node/blob/master/test/integration.js#L375

**Comment by ralphtheninja** [comment]
@Jikstra It's likely due to `greenmail`.
