### ISSUE TITLE
node-gyp doesn't find libsals2 if it's installed globally?!

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#146]
Looks similiar to https://github.com/deltachat/deltachat-node/issues/132 but the exact error is:
```
g++: Fehler: ../deltachat-core/builddir/libs/cyrussasl/libsals2.a: Datei oder Verzeichnis nicht gefunden
```

**Comment by ralphtheninja** [comment]
It's the same problem as for libetpan.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-node/pull/147
