### ISSUE TITLE
File/Folder structure

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#16]
I think we should split the files into dcn_ + first part of function names.
For example, put all those wrapper methods:
-  dcn_msg_get_chat_id
-  dcn_msg_get_duration
-  dcn_msg_get_file
-  dcn_msg_get_filebytes
-  dcn_msg_get_filemime
-  dcn_msg_get_filename
...
-  dcn_msg_get_setupcodebegin
-  dcn_msg_get_showpadlock

into `src/dcn_msg.c`. We will maybe have some files where only one or two methods are in, but i think this shouldn't be too bad.

**Comment by ralphtheninja** [comment]
@r10s has a good point there. Currently it's also easier to add new functions, just comment out and implement the body of the function. Lets see later how this looks. Eventually `src/module.c` might just be too big and something will be done :)

**Comment by Jikstra** [comment]
Hmm didn't see those issues coming up, but sounds like too much trouble for now. We have to face this issue later i guess.
