### ISSUE TITLE
Set up node on r10s machine

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#20]
:wink:

**Comment by r10s** [comment]
is there a readme somewhere? 
i have exactly no idea about node ...

**Comment by ralphtheninja** [comment]
> is there a good read somewhere?

Good question. What system are you using?

**Comment by r10s** [comment]
ubuntu 16.04 LTS

**Comment by ralphtheninja** [comment]
I'm personally using `nvm` https://github.com/creationix/nvm which is a version manager for node. It's very handy if you want to change node versions, you can run a separate shell with one version if you like to test things out.

**Comment by r10s** [comment]
not yet set up, wanted to come back to this issue these days - but i will also do if it is closed :)
