### ISSUE TITLE
Possible to cache or speed up brew?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#224]
`brew install foo` on Travis first does some updating and it takes forever before it even starts installing. It would be really nice if we can speed up this step somehow.

**Comment by ralphtheninja** [comment]
@dignifiedquire Have any tucked away brew wisdom laying around that could help out here? :smile:

**Comment by Jikstra** [comment]
Brew isn't very slow, i think the problem is with travis and the outdated brew. This should be solved as soon as we use the mac in bb33 as a build slave.
