### ISSUE TITLE
Stop providing prebuilds

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-node#246]
I'm proposing to stop providing pre-built Node.js extensions and removing the prebuild machinery from the package.  The prebuild machinery is very nice to produce binaries for different node.js versions etc however it can not cater for multiple openssl versions.  This is a problem since the deltachat extension uses openssl, while nodejs itself also uses openssl and thus these versions need to match exactly.

Instead we should expect deltachat-node users and developers to build their own version of the bindings, improving documentation for the various scenarios where needed.

**Comment by ralphtheninja** [comment]
I see your concerns but expecting everyone to have meson and ninja installed just to use this module is a huge pita if depending on this module. Not to mention all the libraries that deltachat-core depends on. This is the trade off though, just thought I'd mention it.

**Comment by flub** [comment]
On Mon 18 Feb 2019 at 05:48 -0800, Lars-Magnus Skog wrote:

> I see your concerns but expecting everyone to have meson and ninja
> installed just to use this module is a huge pita if depending on this
> module. Not to mention all the libraries that deltachat-core depends
> on. This is the trade off though, just thought I'd mention it.

If someone wants to develop using node, yes they have to go through this
pain.  We can help them by providing clear instructions and also
providing a docker image which can compile and run the deltachat-node
extension module.

But this only affects people who want to develop using node.  Users
should be using the chat.delta.desktop flatpak.

**Comment by flub** [comment]
On Mon 18 Feb 2019 at 05:48 -0800, Lars-Magnus Skog wrote:

> I see your concerns but expecting everyone to have meson and ninja
> installed just to use this module is a huge pita if depending on this
> module. Not to mention all the libraries that deltachat-core depends
> on. This is the trade off though, just thought I'd mention it.

Addressing the huge pita btw, it is a lot easier and better to help them
set up the correct environment than trying to explain why they get
seemingly random problems they need to hack up their system with
symlinks left and right to maybe get things to work.

I'm considering this some sort of meta-issue btw, to achieve this we
need to improve documentation and the build system etc.

**Comment by ralphtheninja** [comment]
> I'm considering this some sort of meta-issue btw, to achieve this we need to improve documentation and the build system etc.

Agreed.

But before addressing any of these issues we should first focus on getting the desktop application building without relying on the node bindings delivering the prebuilt binaries, since this will be the first issue we run into ourselves. By doing this first we will get more information on what needs to change. If we just start by removing prebuilts completely, then desktop ci will break, so this needs to change before we unplug the prebuilts.

**Comment by flub** [comment]
On Mon 18 Feb 2019 at 11:12 -0800, Lars-Magnus Skog wrote:

>> I'm considering this some sort of meta-issue btw, to achieve this we need to improve documentation and the build system etc.
>
> Agreed.
>
> But before addressing any of these issues we should first focus on
> getting the desktop application building without relying on the node
> bindings delivering the prebuilt binaries, since this will be the
> first issue we run into ourselves.

I may be wrong but I thought that was already the case.  For desktop
bindings I'm looking at flatpak and the current flatpak build runs `npm
install/run build/run pack` which I thought would build the
deltachat-node extension from scratch and was expecting to keep working.

> By doing this first we will get
> more information on what needs to change. If we just start by removing
> prebuilts completely, then desktop ci will break, so this needs to
> change before we unplug the prebuilts.

Admittedly I've not looked at CI.  But yes, let's find something that
works for our CI.  What are the things the CI produces?

**Comment by ralphtheninja** [comment]
The CI builds the `.AppImage` etc and attaches to the corresponding GitHub release (`npm run dist-ci`).

**Comment by flub** [comment]
On Mon 18 Feb 2019 at 11:33 -0800, Lars-Magnus Skog wrote:

>  The CI builds the `.AppImage` etc and attaches to the corresponding GitHub release (`npm run dist-ci`).

Ah yes, I'd like to kill the AppImage and .deb builds of
deltachat-desktop in favour of the flatpak.  But I wasn't going to break
that news yet to you ;).  I was trying to ask muelli's (current flatpak
author) opinion first before proposing this.  I think this needs it's
own issue to discuss however.

**Comment by ralphtheninja** [comment]
> Ah yes, I'd like to kill the AppImage and .deb builds of deltachat-desktop in favour of the flatpak. But I wasn't going to break that news yet to you ;). I was trying to ask muelli's (current flatpak author) opinion first before proposing this. I think this needs it's own issue to discuss however.

Well, you asked what the CI produced, and that's the answer.

**Comment by flub** [comment]
:)
