### ISSUE TITLE
Allow building against a system-installed libdeltachat

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-node#247]
Currently the node bindings are setup to automatically pull in deltachat-core from git and invoke the build for it.  This is not what one wants when building their system (or doing packaging works).  In this case you want to be able to build deltachat-node against a carefully-tuned libdeltachat which is already correctly installed on the system with pkg-config files and all.

So from this issue I'd like the following:
- consensus that this is a good idea
- a way to support both the developer workflow (current) and the packager/installer workflow
- how to modify the various npm/build scripts to support both of these correctly

I had a look and think we can use conditionals in the gyp file, but while gyp itself can pass in extra variables I didn't find anything in node-gyp yet to pass this along.

**Comment by ralphtheninja** [comment]
> I had a look and think we can use conditionals in the gyp file, but while gyp itself can pass in extra variables I didn't find anything in node-gyp yet to pass this along.

We're already using conditionals for example for different values of `OS`.

What we need to change to get this working is basically just pointing out the correct include path and path to the librare we're linking with, right? For this reason we could just shell out to `pkg-config` (have a look at the `"include_dirs"` where we're shelling out to node to get include path to `napi-macros`).

**Comment by ralphtheninja** [comment]
I think it's a good idea.

We dont' have to solve everything at once. It should be fine to start by relying on `pkg-config`.

**Comment by flub** [comment]
Oh, it seems we can use pkg-config in the gyp file: https://stackoverflow.com/questions/23378331/using-pkg-config-gyp

But how do we control whether to switch between a build against the system package or do the whole subproject/build-core thing?

**Comment by ralphtheninja** [comment]
> Oh, it seems we can use pkg-config in the gyp file: https://stackoverflow.com/questions/23378331/using-pkg-config-gyp

Yes, which is exactly what I just said :wink: 

> But how do we control whether to switch between a build against the system package or do the whole subproject/build-core thing?

Do we need to? Why not stick to released binaries?

**Comment by flub** [comment]
On Tue, 19 Feb 2019, 00:52 Lars-Magnus Skog <notifications@github.com wrote:

> Oh, it seems we can use pkg-config in the gyp file:
> https://stackoverflow.com/questions/23378331/using-pkg-config-gyp
>
> Yes, which is exactly what I just said 😉
>
Yes, sorry. I didn't know yet how that worked.

> But how do we control whether to switch between a build against the system
> package or do the whole subproject/build-core thing?
>
> Do we need to? Why not stick to released binaries?
>
I was afraid to break to workflow for developers. e.g. you may want to work
with a brand new feature or bugfix in core and use it in node and desktop.
Is this not an important workflow?

**Comment by ralphtheninja** [comment]
> I was afraid to break to workflow for developers. e.g. you may want to work with a brand new feature or bugfix in core and use it in node and desktop. Is this not an important workflow?

We haven't really needed it that badly, but probably useful to have. I'm still a bit hesitant to this change because I suspect we will run into other problems instead, but that's how it goes I guess.

**Comment by ralphtheninja** [comment]
We should have some code in the bindings that checks the version of core and compares it to a minimum version.

**Comment by Jikstra** [comment]
Fixed by https://github.com/deltachat/deltachat-node/pull/257
