### ISSUE TITLE
Build against system OpenSSL on macOS

### ISSUE THREAD

**Issue by tie** [deltachat/deltachat-node#248]
See https://github.com/deltachat/deltachat-desktop/issues/659, https://github.com/deltachat/deltachat-desktop/pull/660.

Any reason why [deltachat-node](https://github.com/deltachat/deltachat-node) does not use system OpenSSL library except it's *considered* outdated?  I've monkey-patched<sup><a id=patch-ref href=#patch>[1]</a></sup> the application and it works fine with `/usr/lib/libssl.dylib` (`libssl.0.9.8.dylib` from macOS Mojave).

Asking the user to manually install or build the dependency is not a solution.  While bundling OK, I can't see any movement in that direction and it could be hard to maintain security updates in a long term.  On the other hand, I doubt Apple will drop support for OpenSSL or introduce breaking changes in the near future — but they still release security updates.

That said, if Delta Chat does not depend on any of the OpenSSL APIs not provided by the latest macOS release (due to the outdated library version), I'd rather define the minimum supported OS release and build against it.  And looks like changing a few lines in [.travis.yml] and [scripts/travis-before-install] should build node bindings against system version of OpenSSL.

<a id=patch href=#patch-ref>[1]</a>: Replaced `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` with `/////////////////////////usr/lib/libssl.dylib` in `Resoureces/app.asar`.

[.travis.yml]: https://github.com/deltachat/deltachat-node/blob/4d1df7542308c3e50dc8569a0765228471e985f1/.travis.yml#L8-L10
[scripts/travis-before-install]: https://github.com/deltachat/deltachat-node/blob/4d1df7542308c3e50dc8569a0765228471e985f1/scripts/travis-before-install#L6

**Comment by Jikstra** [comment]
Not sure if we tried that, i think it caused problems because it was too old. @hpk42 @dignifiedquire do you still remember?

**Comment by tie** [comment]
Oh, and I just found out that macOS actually uses LibreSSL.

```sh
# openssl version
LibreSSL 2.6.5
```

Which is fine too, but it's deprecated<sup>[1]</sup> and no headers are provided<sup>[2]</sup>.

Then there are no other options but to bundle crypto library as part of [deltachat/deltachat-desktop](https://github.com/deltachat/deltachat-desktop).

Sorry for the trouble, closing this issue.

[1]: https://apple.stackexchange.com/questions/324222/how-official-is-libressl-support-in-high-sierra
[2]: https://github.com/rbenv/ruby-build/pull/1095#issuecomment-307540602

**Comment by tie** [comment]
Note that macOS maintains compatibility with programs built against OpenSSL headers (i.e. from an older SDK or source).  That's why my `app.asar` hack<sup>[1]</sup> works.

As a temporary workaround Delta Chat can be built using headers from source but linked against system library.

[1]: 
https://github.com/deltachat/deltachat-node/issues/248#patch
