### ISSUE TITLE
Ship package-lock.json in release tarball

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-node#249]
For downstream packaging we need a the `package-lock.json` file which is generated by  `npm install --package-lock-only`.  I think we want to generate this file as part of the release so that different packagers end up using the same one.

**Comment by ralphtheninja** [comment]
You shouldn't bundle `package-lock.json` in dependencies, only in applications.

**Comment by ralphtheninja** [comment]
https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

**Comment by flub** [comment]
Uh, my bad.  I meant to file this for deltachat-desktop

**Comment by ralphtheninja** [comment]
> Uh, my bad. I meant to file this for deltachat-desktop

Ah, then it makes perfect sense!
