### ISSUE TITLE
Local builds are broken for mac

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#286]
`ldfalgs` should most likely be `ldflags` and some other rpath stuff needs to be tested.

**Comment by ralphtheninja** [comment]
@flub Feel like checking this out tomorrow?

**Comment by flub** [comment]
https://github.com/deltachat/deltachat-node/pull/288 to fix

**Comment by ralphtheninja** [comment]
Builds are compiling and linking now but still some issues. SMTP is not working for me on linux and @nicodh have the same issues on mac.

**Comment by ralphtheninja** [comment]
@flub I'm guessing that if `deltachat.node` is linking with `libdeltachat.so` now, this means we're using system wide installed dependencies of `libdeltachat.so`. For some reason this doesn't work on my machine. If I build `deltachat.node` and use that in desktop I get the following error:

```
'Could not connect to IMAP-server imap.deltachat.net:993 using SSL. (Error #43)'
```

I get the exact same error when trying `deltachat-core-rust` (maybe not surprising).

**Comment by flub** [comment]
Yes, this is the gnutls issue most likely:
https://github.com/deltachat/deltachat-core/issues/544

I have some inspiration to try out there.

**Comment by Jikstra** [comment]
I think we need to still link against the System Frameworks for security...
Adding those lines fixed it some months ago:
```
        [ "OS == 'mac'", {
          "libraries": [
            "../deltachat-core/builddir/src/libdeltachat.a",
            "/usr/local/Cellar/libetpan/1.9.2_1/lib/libetpan.a",
            "/usr/local/lib/rpgp/libpgp_ffi.a",
            "-framework CoreFoundation",
            "-framework CoreServices",
            "-framework Security",
            "-lsasl2",
            "-lssl",
            "-lsqlite3",
            "-lpthread"
]
```

**Comment by flub** [comment]
@ralphtheninja your issue on Debian/Ubuntu/Linux is probably https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927709 aka https://github.com/dinhviethoa/libetpan/pull/330 which you can fix by installing libetpan from source from the master branch.  I had the same issue locally and that fixed it.  If not it should possibly be a separate issue to track?

**Comment by flub** [comment]
@nicodh could you try enabling rpgp in scripts/rebuild-core.js and see if that changes anything here?

**Comment by Jikstra** [comment]
As builds are green again on mac, i think this should get closed? @ralphtheninja @nicodh
