### ISSUE TITLE
Rebuilding on Mac fails

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-node#287]
After commit 6905d96 I get an error when rebuilding on Mac:
`
[63/63] Linking target cmdline/delta.
  CC(target) Release/obj.target/deltachat/src/module.o
../src/module.c:9:10: fatal error: 'deltachat/deltachat.h' file not found
#include <deltachat/deltachat.h>
`

**Comment by ralphtheninja** [comment]
Is this fixed now?

**Comment by Jikstra** [comment]
Is this fixed NOW? :D

**Comment by flub** [comment]
fixed on dc-core master
