### ISSUE TITLE
use rpgp in rebuild-core.js again and update CI to build rpgp

### ISSUE THREAD

**Issue by flub** [deltachat/deltachat-node#297]
rpgp is currently disabled as a shortcut, we should enable it again.

**Comment by Jikstra** [comment]
I propose having a `RPGP=true` environment and in addition to have more control over meson in general, also have OVERWRITE_MESON environment variable which allows us to completely overwrite whatever is run for meson.

**Comment by flub** [comment]
I'm proposing to just always use rpgp, we want to move to it anyway and it avoids having to do another vector in the CI matrix

**Comment by ralphtheninja** [comment]
> I'm proposing to just always use rpgp, we want to move to it anyway and it avoids having to do another vector in the CI matrix

:+1:
