### ISSUE TITLE
Problems connecting to IMAP-server on linux

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#298]
![Screenshot from 2019-04-28 14-16-52](https://user-images.githubusercontent.com/308049/56864238-60316d00-69c0-11e9-8b12-09a572139758.png)

cc @flub Any ideas?

**Comment by ralphtheninja** [comment]
I'm guessing this is related to using my system installed libetpan. I get the exact same error when trying to connect with the rust project (which is expected).

**Comment by flub** [comment]
error #43 i think is indeed the too quick timeout in libetpan issue.  at least that's what i observed locally

**Comment by ralphtheninja** [comment]
Yeap. Will document this in README.
