### ISSUE TITLE
Try out on mac

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#306]
@nicodh This is something you could try on your local machine (the thing I mentioned on last sync meeting):

```
cd /tmp
git clone https://github.com/nodejs/node.git
cd node
git checkout v10.15.3
./configure --shared-openssl --shared-zlib
make -j $(nproc) # go have a huge cup of coffee
sudo ldconfig -v # not sure this is needed or even applicable on mac (think only needed for libraries)
```

Then in your `deltachat-node` folder do (obviously real values for `DC_ADDR` and `DC_MAIL_PW`).

```
DC_ADDR=xxxx DC_MAIL_PW=yyyy /tmp/node/out/Release/node test/integration.js
```

**Comment by nicodh** [comment]
@ralphtheninja thanks for providing the commands, but I run into strange errors I have no clue what they mean...:

`../deps/icu-small/source/common/appendable.cpp:35:13: error: out-of-line definition of 'appendString' does not match any declaration in
      'icu_58::Appendable'
Appendable::appendString(const UChar *s, int32_t length) {
            ^~~~~~~~~~~~

../deps/icu-small/source/common/appendable.cpp:60:13: error: out-of-line definition of 'getAppendBuffer' does not match any declaration in
      'icu_58::Appendable'
Appendable::getAppendBuffer(int32_t minCapacity,
            ^~~~~~~~~~~~~~~
2 errors generated.
make[1]: *** [/Users/ndh/Documents/projekte/deltachat/tmp/node/out/Release/obj.target/icuucx/deps/icu-small/source/common/appendable.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../deps/icu-small/source/common/bytestriebuilder.cpp:19:
../deps/icu-small/source/common/unicode/bytestriebuilder.h:130:22: error: virtual function 'getElementUnit' has a different return type
      ('char16_t') than the function it overrides (which has return type 'UChar' (aka 'unsigned short'))
    virtual char16_t getElementUnit(int32_t i, int32_t byteIndex) const;
            ~~~~~~~~ ^

/opt/local/include/unicode/stringtriebuilder.h:108:19: note: overridden virtual function is here
    virtual UChar getElementUnit(int32_t i, int32_t unitIndex) const = 0;
            ~~~~~ ^

I`

**Comment by nicodh** [comment]
This is the output after running make. Since nproc is not available on mac I just run make -j 4 but also tried different options...

**Comment by ralphtheninja** [comment]
*shrugs*

@nicodh Maybe some hints here? https://github.com/nodejs/node/blob/master/BUILDING.md#unixmacos

**Comment by nicodh** [comment]
Ok I had to update gcc.
But after compiling node and running tests with compiled version (15.3) I still get 
Could not connect to IMAP-server deltachat.de:993 using SSL. (Error #43)
So this didn't help...

**Comment by ralphtheninja** [comment]
Ah ok. Too bad. I'm sort of wondering now what has changed, since this used to work before on mac. Well at first it didn't work, then worked and now not working again :)

**Comment by Jikstra** [comment]
I just compiled and install rpgp on the mac in bb33, updated all brew dependencies and i can successfully connect to my disroot adress with ssl.

**Comment by Jikstra** [comment]
When using libetpan from brew and upgrading it, ci is also happy: https://github.com/deltachat/deltachat-node/pull/313
So I think current master runs on mac just fine.
