### ISSUE TITLE
Rust core hangs on Mac when sending encrypted mail

### ISSUE THREAD

**Issue by nicodh** [deltachat/deltachat-node#311]
When running a test script to send an encrypted mail it hangs without error message. Unencrypted messages are sent as expected.

Is there a way to make debugging more verbose or enable some logging?
I tried RUST_BACKTRACE=1 but that didn't help...

( branch rust-core on Mac )

**Comment by dignifiedquire** [comment]
is there any log output?

**Comment by nicodh** [comment]
Not in console...

**Comment by dignifiedquire** [comment]
Does it just hang or actually crash?

**Comment by nicodh** [comment]
Just hangs. And node process consumes 100% CPU...

**Comment by nicodh** [comment]
@dignifiedquire did you try dc-node on your machine?

**Comment by dignifiedquire** [comment]
yeah, mostly works so far, but there is a known issue with it hanging in the integration tests

**Comment by nicodh** [comment]
Any hint how to improve debugging/logging?

**Comment by dignifiedquire** [comment]
not really right now, the hanging is because there is some deadlock somewhere that I need to find :(

**Comment by nicodh** [comment]
ok

**Comment by dignifiedquire** [comment]
@nicodh there is a new version on deltachat-core-rust master, which fixes the hanging in the tests, could you try that out and see if this solves this issue please?

**Comment by nicodh** [comment]
Tried it, but it didn't help... :-(
The integration in rust-core tests seem to be fine on my machine...

**Comment by ralphtheninja** [comment]
> When running a test script to send an encrypted mail it hangs without error message

@nicodh Which script is this? It might be hanging not just for mac.

**Comment by nicodh** [comment]
Well what I did is a temporary change in test/integration.js:
`const cwd = path.dirname('LOCAL_PATH_TO_CONFIG') // instead of tempy.directory()
  const chat_id = 55
  dc = new DeltaChat()
  dc.once('ready', () => {
    console.log('sendMessage');
    dc.sendMessage(chat_id, 'Test message')
    console.log('message sent');
  })`
Where chat_id is a chat, where messages are encrypted.
If I do the same for a not encrypted chat (like a new created one to a new created contact) it works fine and the message is sent...

**Comment by ralphtheninja** [comment]
@nicodh Where is `cwd` passed to `DeltaChat()`? You need to do `dc.open()`, see desktop code: https://github.com/deltachat/deltachat-desktop/blob/04294428eaf502a0ad6030683502d0f5c588e3cc/src/main/deltachat.js#L63-L81

You shouldn't need to configure here since I'm guessing you want to try an already configured folder, right?

**Comment by ralphtheninja** [comment]
Sorry if I'm seeing this a little bit out of context. Mind just pasting the complete script to a gist? (or in here).

**Comment by nicodh** [comment]
I did it like this since I didn't know how to send an encrypted message except for an existing chat 
https://gist.github.com/nicodh/e3e4c15f1c7d13d394863141991b29de
The example for a new contact is commented...

**Comment by nicodh** [comment]
Just a quick hack since I'm quite busy with other stuff at the moment...
I just wanted to figure out, where the problem occurs and my first test (with a new contact and chat) worked, so that's how I came up with the idea to use an existing one...

**Comment by ralphtheninja** [comment]
I'm closing this. It works in desktop.
