### ISSUE TITLE
Improve the way we destroy a dc context

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#321]
At the moment we rely on v8 to garbage collect objects from core. This works roughly as follows:

* a call to `napi_create_external()` is made to wrap a c pointer, which is returned back to javascript
* in the call to `napi_create_external()` a pointer to a function is passed, which gets called when v8 garbage collects the corresponding javascript object
* the c function then cleans up the underlying dc object, e.g. by calling `dc_context_unref()`, `dc_chat_unref()`, `dc_contact_unref()` etc

This works, but if _any_ of these `dc_xyz_unref()` takes a lot of time, it means the v8 thread will hang, which in turn causes the desktop application to hang until this is done.

It seems to me that this only happens for `dc_context_unref()`, which I assume is doing much more under the hood.

In any case, there are two approaches here:

1. try to figure out why `dc_context_unref()` takes a lot of time, fix that and pretend it's raining
1. make e.g. `dc.close()` async, and call `dc_context_unref()` explicitly, i.e. this function should _not_ be called by the v8 thread during garbage collection

The second option is probably the most correct and more future proof way of doing it. Obviously we can also combine this with the first option.

Related: https://github.com/deltachat/deltachat-node/issues/80 and https://github.com/deltachat/deltachat-node/pull/308#discussion_r285103580

**Comment by Jikstra** [comment]
I think we should make it async. We had that idea a long time ago already ^^

**Comment by ralphtheninja** [comment]
@Jikstra Do you have anything against me merging the rust-core branch already and then start working on async dc.close()?

**Comment by ralphtheninja** [comment]
@Jikstra Nevermind, just saw your answer in the PR. I'll start working on async `dc.close()` after this.
