### ISSUE TITLE
Make calls into deltachat-core async

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#35]
We should use callbacks for most functions since some calls takes a bit of time and this blocks everything in the javascript main thread (well duh).

**Comment by r10s** [comment]
i can describe what we have done in the Android part:

1. when the documentation says "call them from a thread" we do this :) eg. [`dc_initiate_key_transfer()`](https://deltachat.github.io/api/classdc__context__t.html#af327aa51e2e18ce3f5948545a637eac9) or [`dc_join_securejoin()`](https://deltachat.github.io/api/classdc__context__t.html#ae49176cbc26d4d40d52de4f5301d1fa7) are called from a thread ("thread" in this sense is not the imap-thread or smtp-thread but a ui-created worker thread that does not much more than calling the destination function).

2. functions doing more or less complex database queries, are "fast enough" in my experience, but for the "global search", that combines some of them, things may get too slow; reported eg [here](https://deltachat.github.io/api/classdc__context__t.html#a777bb1e11d7ea0288984ad23c2d8663b).  
so, it may makes sense to call [`dc_get_chatlist()`](https://deltachat.github.io/api/classdc__context__t.html#a709a7b5b9b606d85f21e988e89d99fef) or [`dc_search_msg()`]() and probably some more from a thread. i've planned this also for Android.

3. finally, functions operating mainly on objects in memory as `dc_msg_*()`, `dc_chat_*()`, `dc_chatlist_*()`, `dc_contact_*()`, `dc_lot_*()` (name subject to change :), `dc_array_*()` should be "fast enough" as they do no i/o. i think this is the majority - these functions mainly return a value from an object from memory, i do not think it makes much sense to call them in a thread.

so in general, most functions are fast and i would start optimizing only on places that feel "slow" :)

**Comment by ralphtheninja** [comment]
Nice feedback! At the moment I'll not care about sync vs async. Most important thing is to get some sort of api up and running. Some stuff doesn't make any sense to have async and some do. Key take away here, is to try and picture the desktop application as the primary user of the node bindings. If _any_ call blocks for 100 ms, this will have effect on the ui as well.

Maybe we can start migrating functions one at a time, as we noticed what takes time etc.

**Comment by Jikstra** [comment]
In my opinion we should make all calls which use the database in any way async, otherwise, as ralph already said, this will block the main/"ui" thread in nodejs. Maybe even open & close calls. What we can do, postfix all the methods which use the database and we don't want to make them async for now, but maybe implement a async method later, postfix with _sync. This is a known standard way in nodejs (see fs module for example). I don't think that implementing this is hard, but we need to figure out a good pattern to follow for this.

**Comment by ralphtheninja** [comment]
Postfixing with `_sync` sounds like a good idea. Actually we could postfix _all_ methods right now and once we make functions async we remove the postfix. It will also help us remember which ones are sync or async when working on the code.

**Comment by ralphtheninja** [comment]
Lets close this and open issues for _specific_ functions that need to be async. It's too broad.
