### ISSUE TITLE
No win64 prebuilts

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#353]
Currently there are only 32bit prebuilts, i think it makes sense to also have 64bit.

**Comment by ralphtheninja** [comment]
There are 64 bit prebuilts and not 32 bit.

**Comment by ralphtheninja** [comment]
```
$ tree node_modules/deltachat-node/prebuilds/
node_modules/deltachat-node/prebuilds/
├── darwin-x64
│   └── node.napi.node
├── linux-x64
│   └── node.napi.node
└── win32-x64
    ├── deltachat.dll
    └── node.napi.node

3 directories, 4 files
```

**Comment by Jikstra** [comment]
Hmm okay. I currently set up a win10 virtual box with npm/nodejs and try to `npm install deltachat-node`. But it falls back to from source compilation. To which nodejs/windows versions is this compatible? Any ideas how i can find this out?

**Comment by ralphtheninja** [comment]
What does `node -p process.platform` and `node -p process.arch` say on that virtual machine?

**Comment by Jikstra** [comment]
win32 and x64. So this should be correct. Will try it out again.

**Comment by ralphtheninja** [comment]
@Jikstra Also, do `npm i --verbose` since we get more information in case it fails to load with `node-gyp-build` here https://github.com/prebuild/node-gyp-build/blob/master/bin.js#L10

**Comment by ralphtheninja** [comment]
Also, node itself needs to be at least version 10. Which version are you running on that machine?

**Comment by Jikstra** [comment]
Hmm removing node modules and doing a npm install again fixed it. Fucking npm.
