### ISSUE TITLE
Mac builds broken?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#356]
![Screenshot from 2019-06-29 13-25-36](https://user-images.githubusercontent.com/308049/60383477-9008f980-9a71-11e9-9de3-28828d836217.png)

https://travis-ci.org/deltachat/deltachat-node/jobs/552072746

**Comment by ralphtheninja** [comment]
@flub Any idea? cc @Jikstra @nicodh

**Comment by nicodh** [comment]
Can't reproduce it on my mac...

**Comment by flub** [comment]
hmm, https://github.com/filecoin-project/go-filecoin/issues/2292#issuecomment-474145857 seems to suggest that this might be mixing results from different rust compiler versions?  Is there a cache somehow that resulted in an object compiled by the previous rust-nightly to be used?  Did the CI here not pick up the newer rust-toolchain file?

**Comment by Jikstra** [comment]
Cache? It's weird, I mean we compile it on that same host, so why should the mac versions differ?

**Comment by ralphtheninja** [comment]
At first when we install rust it says:

```
27.48s$ ./ci_scripts/ci-prelude.sh
+DC_CORE_VERSION=master
+'[' -z osx ']'
+SYS_DC_CORE=false
+curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs
+sh -s -- --default-toolchain nightly -y
info: downloading installer
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2019-06-29, rust version 1.37.0-nightly (433a46781 2019-06-28)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'nightly'
  nightly installed - rustc 1.37.0-nightly (433a46781 2019-06-28)
```

Then when actually building rust core it syncs (to an older version):

```
>> spawn: cargo update
info: syncing channel updates for 'nightly-2019-04-19-x86_64-apple-darwin'
info: latest update on 2019-04-19, rust version 1.36.0-nightly (5d20ff4d2 2019-04-18)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
    Updating crates.io index
```

Gonna try updating to `alpha.1` to see if this problem is simply because of a mismatch.
