### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-node#359]
relevant part of output:
```
> deltachat-node@1.0.0-alpha.0 node-gyp-build /home/simon/Documents/Projects/delta-irc-bridge/node_modules/deltachat-node
> node-gyp-build "node scripts/rebuild-core.js" "node scripts/postinstall.js"

    Updating crates.io index
error: failed to parse manifest at `/home/simon/Documents/Projects/delta-irc-bridge/node_modules/deltachat-node/deltachat-core-rust/Cargo.toml`

Caused by:
  can't find `simple` example, specify example.path
cargo failed with code 101
```

**Comment by ralphtheninja** [comment]
This has most likely nothing to do with the node bindings. Transfer it to core?

**Comment by ralphtheninja** [comment]
Hmm, it's working on my machine.

**Comment by Simon-Laux** [comment]
installing only dc node works for me too, but as soon as I install it in my project with ```npm i --save https://github.com/deltachat/deltachat-node.git#8f73ad58849b8b837f742ead84ee0f1d7f988ed0
```
I get this error

**Comment by ralphtheninja** [comment]
I'm thinking it might be related to git submodule.

**Comment by ralphtheninja** [comment]
Can't we just release `alpha.1` instead?

**Comment by Simon-Laux** [comment]
It says there is the path missing for the simple example -> Cargo toml is invalid
and then it panics and "crashes"

**Comment by Simon-Laux** [comment]
can we set the submodule to a84e4959f6c0481b261101d8485361df58f657a0 ? to test it?

**Comment by ralphtheninja** [comment]
@Simon-Laux Just push a branch with that and try it. I'm releasing alpha.1 mean while.

**Comment by Simon-Laux** [comment]
> Can't we just release alpha.1 instead?

We can, but I would like to see this solved before. Also I'm not logged in into npm and don't know how the release an npm module thingie works yet/

**Comment by ralphtheninja** [comment]
The solution is to release a new version. It's currently not designed to be installed on a random commit due to git submodule. That's my theory at least.

**Comment by ralphtheninja** [comment]
> Also I'm not logged in into npm and don't know how the release an npm module thingie works yet/

I'm releasing it right now.

**Comment by ralphtheninja** [comment]
@Simon-Laux It seems it works with your fix. What was wrong with Cargo.toml?

**Comment by Simon-Laux** [comment]
I don't know I read the error and figured removing it could help... also adding the path could help, but I'm not sure whether it was removed on purpose. 
I'm sure @dignifiedquire will find a better solution so we shouldn't merge it. https://github.com/deltachat/deltachat-core-rust/pull/166#issuecomment-507456948

**Comment by nicodh** [comment]
I remember having that error some weeks (months?) ago but can't remember how I fixed it. But probably not an error with core...

**Comment by dignifiedquire** [comment]
you could try adding `path = "examples/simple.rs"`
