### ISSUE TITLE
Env var for debug builds

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-node#370]
useful for development, needed for https://github.com/deltachat/deltachat-desktop-dev-env/issues/12

The idea is to have an environment variable to toggle (dc-core-rs) debug builds and linking to those debug builds.

**Comment by Jikstra** [comment]
Including debug symbols works with executing
`RUSTFLAGS=-g npm run rebuild-all`

**Comment by Simon-Laux** [comment]
Thanks that did the trick
