### ISSUE TITLE
Change license to GPL-3.0-or-later?

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-node#373]
See https://github.com/deltachat/deltachat-desktop/issues/987

That requires agreement from all the major contributors, but solves license incompatibility with deltachat-desktop and problems if GPL-3.1 or GPL-4.0 is released in the future.

**Comment by Jikstra** [comment]
@ralphtheninja 
@nicodh 
@r10s 
@okdistribute 
@flub 
@Simon-Laux 

Are you fine with changing license to GPL-3.0-or-later?

**Comment by nicodh** [comment]
Fine for me

**Comment by r10s** [comment]
fine for me

**Comment by ralphtheninja** [comment]
Lets do it.

**Comment by flub** [comment]
sure, i'm fine with extending my faith in the FSF future licensing whims

**Comment by Simon-Laux** [comment]
I'm fine with it.

Am 18. September 2019 11:30:06 MESZ schrieb Jikstra <notifications@github.com>:
>@ralphtheninja 
>@nicodh 
>@r10s 
>@okdistribute 
>@flub 
>@Simon-Laux 
>
>Are you fine with changing license to GPL-3.0-or-later?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-node/issues/373#issuecomment-532603643

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by hpk42** [comment]
On Wed, Sep 18, 2019 at 02:30 -0700, Jikstra wrote:
> @ralphtheninja 
> @nicodh 
> @r10s 
> @okdistribute 
> @flub 
> @Simon-Laux 
> 
> Are you fine with changing license to GPL-3.0-or-later?

also merlinux is fine ;) note that licensing rights partly 
are with merlinux, when folks have done things under contract.

**Comment by okdistribute** [comment]
awesome!
