### ISSUE TITLE
Postfix all functions with _sync

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#38]
See https://github.com/deltachat/deltachat-node/issues/35#issuecomment-408644509

This should be done before even considering making some functions async.

**Comment by Jikstra** [comment]
Not all methods. Only for those where we want to implement async methods. Setting an event handler is totally fine to do it synchronously. But opening the database, retrieving ids... If we're unsure if a async method is needed, we better set it sync. Benefit of this is, that we don't need to deprecate any methods and implementing async methods won't break backwards compatibility.

**Comment by ralphtheninja** [comment]
> Maybe not for all methods?

Why not? How would a user of the api know whether a method is sync or async?

**Comment by ralphtheninja** [comment]
Lets just do it _our_ way for now :)
