### ISSUE TITLE
Travis should run example-binding.js with some test credentials for the moment

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#39]
The "build passing" badge isn't saying too much, currently we know it builds if example-binding.js isn't throwing an error. For the short we could set an email & password as a travis environment variable (as it's done with github api tokens/keys) and hide them from the build output, and in the .travis.yml do something like `node example-binding.js --email $EMAIL --password $EMAIL_PASSWORD`. This should be easy to do (i hope so :D) and help for the moment until we fixed https://github.com/deltachat/deltachat-node/issues/24.

**Comment by ralphtheninja** [comment]
Awesome idea!

**Comment by ralphtheninja** [comment]
Closing in favor of https://github.com/deltachat/deltachat-node/issues/47
