### ISSUE TITLE
best way to relay msg?

### ISSUE THREAD

**Issue by cracker0dks** [deltachat/deltachat-node#398]
I want to create a bot to relay messages to others.

Don't working:
```
dc.on('DC_EVENT_INCOMING_MSG', (chatIdFrom, msgId) => {
    const msg = dc.getMessage(msgId);
    dc.sendMessage(otherChatId, msg);
}
```

`Error: 400 0 peerstate for [email] missing, cannot encrypt`

If I relay like this:
```
dc.on('DC_EVENT_INCOMING_MSG', (chatIdFrom, msgId) => {
    const msg = dc.getMessage(msgId);
    const msgTxt = msg.getText();
    dc.sendMessage(otherChatId, msgTxt );
}
```
In this case I also get the log:
`Error: 100 0 peerstate for [email] missing, cannot encrypt`

but not a 400 and It works. But for text only ofc. 
I don't want to catch all types of different messages so is there a easy way to relay the hole msg obj? Thanks :)

**Comment by Simon-Laux** [comment]
I would reconstruct it, otherwise your sending a existing message again, which can in theory make problems later. 
Also it might make sense to expand the forward message api to optionaly don't include the notice that it was forwarded (if that is possible).

**Comment by cracker0dks** [comment]
ok, ty
