### ISSUE TITLE
add Option to specify core directory via env var

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-node#400]
would enable us to solve https://github.com/deltachat/deltachat-desktop-dev-env/issues/12

links that might be useful:
https://gyp.gsrc.io/docs/InputFormatReference.md#user_defined-variables
https://stackoverflow.com/questions/32071731/can-i-use-environment-variable-in-gyp#32628422

**Comment by hpk42** [comment]
Not sure i understand.  Do you know that if you set env var "RUSTFLAGS=-g"
that a cargo-build will produce debug symbols even if building a release?

**Comment by Jikstra** [comment]
More or less done, install libdeltachat with cmake and have pkg-config properly set. Then do `USE_SYSTEM_LIBDELTACHAT="true" npm i`. Make sure `pkg-config --libs deltachat` and `pkg-config --cflags deltachat` returns good things.
