### ISSUE TITLE
asyncify joinSecurejoin (convert callback to promise)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-node#459]
```ts
// current
joinSecurejoin(code:string, callback:(result:number)=>()):void
// wanted
joinSecurejoin(code:string):Promise<number>
```

ah while we are already at it, we should add a doc comment stating that the result is the joined chat id.

### Why is this urgent?
Because the cb argument is not a real callback (contains no error), also the error on fail is thrown somewhere, but not at the place `joinSecurejoin` was called.
So wrapping the current function in a promise within js **is not enough**, the throwing of the error needs to be fixed in the napi module as well.

**Comment by Jikstra** [comment]
There should be no error thrown. join_securejoin on the cffi doesnt throw any errors and only returns an integer. Where should the error come from?
