### ISSUE TITLE
Wrap the current api

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#5]
The current api is really low level (which is cool) but it should be wrapped by an object so instead of doing:

```js
var context = new deltachat.dc_context_new(cb)
var contact = deltachat.dc_get_contact(context, contact_id)
```

We can do something like:

```js
var dc = DeltaChat(cb)
var contact = dc.get_contact(contact_id)
```

I.e. we hide the `context` to make it a bit more cleaner. It could instead be handled internally.

**Comment by karissa** [comment]
yeah sounds good

**Comment by karissa** [comment]
@ralphtheninja https://github.com/deltachat/deltachat-node/pull/6
