### ISSUE TITLE
Signature reverts to default when I set it to nothing

### ISSUE THREAD

**Issue by hut** [deltachat/deltachat-node#505]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.14.1
- Expected behavior: When I set the signature to an empty string, I expect no signature to be sent. This is the behavior on the android app as well.
- Actual behavior: On deltachat desktop, it reverts to the default signature instead as soon as I close the settings window.
- Steps to reproduce the problem: Open settings, Edit Profile, Clear the "Signature text" field, Click "Ok" and then "Close", Open settings and edit profile again. The default signature is used again.

Thank you

**Comment by Simon-Laux** [comment]
When changing this that it accepts is `null` we need to make sure that all settings in desktop still work as expected, not that we introduce other bugs while fixing this.

**Comment by r10s** [comment]
yip, one should be careful with these kind of things. 

nb: one higher level, `NULL` in converted to `""` the https://github.com/deltachat/deltachat-node/blob/2088a99561115c20fbf1f91a6f14fb2579e232c6/lib/deltachat.ts#L822 :)

so, maybe remove both guards and check carefully all explicit/implicit calls to `dc_set_config()`, that there are no side-effects.
