### ISSUE TITLE
Remove binding.js, no longer useful

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#63]

**Comment by Jikstra** [comment]
Why is it not longer useful? Isn't it possible to require('deltachat-node/binding') if you only want to have the low level bindings pulled in?

**Comment by ralphtheninja** [comment]
> Why is it not longer useful? Isn't it possible to do require('deltachat-node/binding') if you only want to have the low level bindings pulled in?

Right, forgot about that :)
