### ISSUE TITLE
Implementation status of deltachat-core api

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#7]
- [x] `dc_add_address_book`
- [x] `dc_add_contact_to_chat`
- [x] `dc_archive_chat`
- [x] `dc_array_get_cnt`
- [x] `dc_array_get_id`
- [x] `dc_array_get_ptr`
- [x] `dc_array_get_uint`
- [x] `dc_array_unref`
- [x] `dc_block_contact`
- [x] `dc_chat_get_archived`
- [x] `dc_chat_get_draft_timestamp`
- [x] `dc_chat_get_id`
- [x] `dc_chat_get_name`
- [x] `dc_chat_get_profile_image`
- [x] `dc_chat_get_subtitle`
- [x] `dc_chat_get_text_draft`
- [x] `dc_chat_get_type`
- [x] `dc_chat_is_self_talk`
- [x] `dc_chat_is_unpromoted`
- [x] `dc_chat_is_verified`
- [x] `dc_chat_unref`
- [x] `dc_chatlist_get_chat_id`
- [x] `dc_chatlist_get_cnt`
- [x] `dc_chatlist_get_context`
- [x] `dc_chatlist_get_msg_id`
- [x] `dc_chatlist_get_summary`
- [x] `dc_chatlist_unref`
- [x] `dc_check_password`
- [x] `dc_check_qr`
- [x] `dc_close`
- [x] `dc_configure`
- [x] `dc_contact_get_addr`
- [x] `dc_contact_get_display_name`
- [x] `dc_contact_get_first_name`
- [x] `dc_contact_get_id`
- [x] `dc_contact_get_name`
- [x] `dc_contact_get_name_n_addr`
- [x] `dc_contact_is_blocked`
- [x] `dc_contact_is_verified`
- [x] `dc_contact_unref`
- [x] `dc_context_new`
- [x] `dc_context_unref`
- [x] `dc_continue_key_transfer`
- [x] `dc_create_chat_by_contact_id`
- [x] `dc_create_chat_by_msg_id`
- [x] `dc_create_contact`
- [x] `dc_create_group_chat`
- [x] `dc_delete_chat`
- [x] `dc_delete_contact`
- [x] `dc_delete_msgs`
- [x] `dc_forward_msgs`
- [x] `dc_get_blobdir`
- [x] `dc_get_blocked_cnt`
- [x] `dc_get_blocked_contacts`
- [x] `dc_get_chat`
- [x] `dc_get_chat_contacts`
- [x] `dc_get_chat_id_by_contact_id`
- [x] `dc_get_chat_media`
- [x] `dc_get_chat_msgs`
- [x] `dc_get_chatlist`
- [x] `dc_get_config`
- [x] `dc_get_config_int`
- [x] `dc_get_contact`
- [x] `dc_get_contact_encrinfo`
- [x] `dc_get_contacts`
- [x] `dc_get_fresh_msg_cnt`
- [x] `dc_get_fresh_msgs`
- [x] `dc_get_info`
- [x] `dc_get_msg`
- [x] `dc_get_msg_cnt`
- [x] `dc_get_msg_info`
- [x] `dc_get_next_media`
- [x] `dc_get_securejoin_qr`
- [x] `dc_get_userdata`
- [x] `dc_imex`
- [x] `dc_imex_has_backup`
- [x] `dc_initiate_key_transfer`
- [x] `dc_interrupt_imap_idle`
- [x] `dc_interrupt_smtp_idle`
- [x] `dc_is_configured`
- [x] `dc_is_contact_in_chat`
- [x] `dc_is_open`
- [x] `dc_join_securejoin`
- [x] `dc_lot_get_id`
- [x] `dc_lot_get_state`
- [x] `dc_lot_get_text1`
- [x] `dc_lot_get_text1_meaning`
- [x] `dc_lot_get_text2`
- [x] `dc_lot_get_timestamp`
- [x] `dc_lot_unref`
- [x] `dc_marknoticed_chat`
- [x] `dc_marknoticed_contact`
- [x] `dc_markseen_msgs`
- [x] `dc_msg_get_chat_id`
- [x] `dc_msg_get_duration`
- [x] `dc_msg_get_file`
- [x] `dc_msg_get_filebytes`
- [x] `dc_msg_get_filemime`
- [x] `dc_msg_get_filename`
- [x] `dc_msg_get_from_id`
- [x] `dc_msg_get_height`
- [x] `dc_msg_get_id`
- [x] `dc_msg_get_mediainfo`
- [x] `dc_msg_get_setupcodebegin`
- [x] `dc_msg_get_showpadlock`
- [x] `dc_msg_get_state`
- [x] `dc_msg_get_summary`
- [x] `dc_msg_get_summarytext`
- [x] `dc_msg_get_text`
- [x] `dc_msg_get_timestamp`
- [x] `dc_msg_get_type`
- [x] `dc_msg_get_width`
- [x] `dc_msg_is_forwarded`
- [x] `dc_msg_is_increation`
- [x] `dc_msg_is_info`
- [x] `dc_msg_is_sent`
- [x] `dc_msg_is_setupmessage`
- [x] `dc_msg_is_starred`
- [x] `dc_msg_latefiling_mediasize`
- [x] `dc_msg_new`
- [x] `dc_msg_set_dimension`
- [x] `dc_msg_set_duration`
- [x] `dc_msg_set_file`
- [x] `dc_msg_set_mediainfo`
- [x] `dc_msg_set_text`
- [x] `dc_msg_set_type`
- [x] `dc_msg_unref`
- [x] `dc_open`
- [x] `dc_openssl_init_not_required`
- [x] `dc_perform_imap_fetch`
- [x] `dc_perform_imap_idle`
- [x] `dc_perform_imap_jobs`
- [x] `dc_perform_smtp_idle`
- [x] `dc_perform_smtp_jobs`
- [x] `dc_remove_contact_from_chat`
- [x] `dc_search_msgs`
- [x] `dc_send_audio_msg`
- [x] `dc_send_file_msg`
- [x] `dc_send_image_msg`
- [x] `dc_send_msg`
- [x] `dc_send_text_msg`
- [x] `dc_send_vcard_msg`
- [x] `dc_send_video_msg`
- [x] `dc_send_voice_msg`
- [x] `dc_set_chat_name`
- [x] `dc_set_chat_profile_image`
- [x] `dc_set_config`
- [x] `dc_set_config_int`
- [x] `dc_set_text_draft`
- [x] `dc_star_msgs`
- [x] `dc_stop_ongoing_process`

**Comment by ralphtheninja** [comment]
@r10s There are a lot of methods and maybe we should try to pick the most important first. In your opinion, which ones are the most important to get started?

cc @Jikstra @hpk42

**Comment by ralphtheninja** [comment]
I think we should also try to implement them in groups. For example, it doesn't make sense to implement `dc_set_config` and then do something completely unrelated, i.e. maybe finish `dc_get_config`, `dc_set_config_int`, `dc_get_config_int` at the same time.

**Comment by r10s** [comment]
@ralphtheninja cc @Jikstra - yes, implementing them in groups makes sense.

- apart from that i would roughly start with  dc_create_contact(), dc_create_chat_by_contact_id() and dc_send_text_msg() - this allows us to send a first message.

- then i would suggest to implement the functions as needed - this way they will also get tested directly and we do not risk to do work twice if the core-api changes in between (beside the [*draft*()](https://github.com/deltachat/deltachat-core/issues/214) functions it is not planned, however, it may happen, esp. for the *qr*()-functions)

- the dc_perfrom_*() functions can be skipped directly as they are are  called in the napi-part. i've marked them above as being done.

- the dc_interrupt_*() are possibly also not needed at all

**Comment by ralphtheninja** [comment]
`dc_get_config`, `dc_get_config_int` and `dc_set_config_int` implemented.

**Comment by ralphtheninja** [comment]
@r10s Cool. I think we're on the same page here. Pulling in functions as we need them is much better than trying to implement everything and have no idea of if the functions work or not.

So lets implement the following as you recommended:

* `dc_create_contact`
* `dc_create_chat_by_contact_id`
* `dc_send_txt_msg`
* `dc_get_info`

And release `0.0.1`. We can keep implementing a while until we feel that the module is "ready" and then release a `1.0.0`. Imo, semver in node/npm works best if you already have a major version out.

**Comment by r10s** [comment]
wrt style: i would suggest to divide the wrapper functions to three parts divided by an empty line - get-parameters, call-to-c, return-value. Example:

```
NAPI_METHOD(dcn_send_text_msg) {
  NAPI_ARGV(3);
  NAPI_DCN_CONTEXT();
  NAPI_INT32(chat_id, argv[1]);
  NAPI_UTF8(text, argv[2]);

  uint32_t msg_id = dc_send_text_msg(dcn_context->dc_context, chat_id, text);

  NAPI_RETURN_INT32(msg_id);
}
```

makes sense?

**Comment by r10s** [comment]
another comment to the dc_array_*() functions: in the Java-Binding we do not return dc_array_t but return a native integer-array directly. 

maybe this is also possible in napi; if so, the full array can be accessed from napi (not from js) using [dc_array_get_raw()](https://deltachat.github.io/api/classdc__array__t.html#a0fd0d960ecbea43d11fdc8046e3c9e63) (documentation added, was missing before)

**Comment by ralphtheninja** [comment]
> makes sense?

Makes sense! Feel free to PR a clean up of this :)

**Comment by r10s** [comment]
i do :) (but first i am for lunch :)

**Comment by ralphtheninja** [comment]
> i do :) (but first i am for lunch :)

Please re-clone this repository (or change remote with git).

**Comment by r10s** [comment]
> Please re-clone this repository (or change remote with git).

too late for #18 - @ralphtheninja @Jikstra so, currently we only have one deltachat-node repo and the old deltachat-node-bindings are included there?

**Comment by ralphtheninja** [comment]
It's not really needed to switch remote if you rename a repository (github will notice this but will tell you to please change remote).

We now have

* `deltachat-node` (this repo)
* `deltachat-node-legacy` (the previous `deltachat-node`, which is now archived)

**Comment by r10s** [comment]
i've re-cloned it, np.

it is okay for you if i do my pr from branches in deltachat/deltachat-node (as the last few PRs).
this way feels always a little simpler to me instead of using eg. r10s/deltachat-node.

**Comment by ralphtheninja** [comment]
> it is okay for you if i do my PRs from branches in deltachat/deltachat-node (as the last few PRs)?
> this way feels always a little simpler to me instead of using eg. r10s/deltachat-node.

Perfectly fine. But I try to squash the PRs and clean up the branches afterwards.

**Comment by ralphtheninja** [comment]
> another comment to the dc_array_*() functions: in the Java-Binding we do not return dc_array_t but return a native integer-array directly.

I haven't looked too much into this yet, but I think the js bindings should assume as little as possible and just call into c. Then we put a higher level api on top of that, so the low level api is doing low level stuff and the higher level api can return an array of js objects.

**Comment by r10s** [comment]
i agree.

i was thinking about performance maybe too much. assume [dc_get_chat_msgs()](https://deltachat.github.io/api/classdc__context__t.html#a51353ff6b85fa9278d2ec476c3c95eda) returns 1000 message IDs:

1. returning an js-array may be as cheap as a memcpy() ([corresponding Java-code](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/jni/mrwrapper.c#L95))
2. returning an (from js land) opaque c-array needs lots of context switches between js and c

however, start to thinking further, a typical node implementation will probably not access _all_ elements but only the one currently scrolled to. from this point of view, a dcn_array_get_id() seems not to be a big deal as it is typically followed by an even more expensive call that load things from the database, eg. to [dc_get_msg()](https://deltachat.github.io/api/classdc__context__t.html#a4fd6b4565081c558fcd6ff827f22cb01)

**Comment by ralphtheninja** [comment]
All functions implemented! :champagne:

**Comment by karissa** [comment]
wow great job @ralphtheninja !
