### ISSUE TITLE
Translating strings (DC_EVENT_GET_STRING)

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#70]
I get a tonne of these now when playing around with the api. Maybe we can take the strings below and pass in at startup somehow?

![screenshot from 2018-08-09 03-47-00](https://user-images.githubusercontent.com/308049/43873504-0e78047c-9b87-11e8-8a68-181dc578b799.png)

cc @r10s

**Comment by r10s** [comment]
in general, we could do so.

however. it gets a little more complicated as the core has to handle several plural forms of different languages. 

currently, this is up to the user of the library (eg. android and ios typically provide their own translation systems, the idea was just to use it.

maybe we can leave the message system "as is" and add an extra layer for node.js.

**Comment by ralphtheninja** [comment]
I removed these events for now, since they aren't doing anything.
