### ISSUE TITLE
Put back push mechanism once electron supports node v10.6.0

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#79]
Just making an issue for it. Might take a while.

**Comment by ralphtheninja** [comment]
Also, when we do this, we need to make sure that `deltachat-core` uses an openssl version that's compatible with this version of node/electron.

**Comment by Jikstra** [comment]
Electron 4 now uses node v.10.11.0 which should be enough for us.
https://electronjs.org/releases#4.0.0

**Comment by ralphtheninja** [comment]
@Jikstra Lets wait a little bit. As @karissa mentioned, the first couple of releases of electron most surely has some bugs. This is good news though, that soon we will be able to leave the polling mechanism behind. (We should/could play with this at 35c3).

**Comment by Jikstra** [comment]
Yup better wait a bit. I just wanted to notice this down. It took quite some time until electron 3 was "ready", i remember that bug of substack ^^

**Comment by ralphtheninja** [comment]
Done in https://github.com/deltachat/deltachat-node/commit/3526adb47bc2f183cc585d3d2c4905b8fd265360
