### ISSUE TITLE
Test build on osx

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#8]

**Comment by ralphtheninja** [comment]
I've done some initial work on the `osx` branch, but I'm currently waiting for @flub 's work on `deltachat-core` before I continue.

**Comment by flub** [comment]
See https://github.com/flub/deltachat-core/tree/openssl for this.  For OSX I'd start with `meson --default-library=static` (which is i believe what you want but you can build shared too if you like) without any arguments (i.e. use what's on the system but with fallback.  I'd try to install zlib and openssl on the system and see if it can use them, let the others depend on the fallback and see how that goes.

To try using all the bundled libs, but you may have some very suboptimal openssl implementations, you can add `meson --default-library=static --wrap-mode=forcefallback`.  On the plus side it's more repeatable and you do not have to install any dependencies.

**Comment by flub** [comment]
I'll create a PR for that branch once I've updated the README.

**Comment by ralphtheninja** [comment]
> See https://github.com/flub/deltachat-core/tree/openssl for this. For OSX I'd start with `meson --default-library=static` (which is i believe what you want but you can build shared too if you like) without any arguments (i.e. use what's on the system but with fallback. I'd try to install zlib and openssl on the system and see if it can use them, let the others depend on the fallback and see how that goes.

My main issue is actually getting `sasl` to compile.

**Comment by ralphtheninja** [comment]
Current status:

* updated meson (0.45.1 is not enough)
* build works fine, i.e. `meson --default-library=static --wrap-mode=forcefallback`
* symbol lookup error: `/home/lms/src/deltachat/deltachat-node/build/Debug/deltachat.node: undefined symbol: CRYPTO_num_locks` (I get this error during runtime, not during compile time)
* build log here: https://gist.github.com/ralphtheninja/5753028dffc3df35ea89873d12b4c2bc

**Comment by ralphtheninja** [comment]
Build works fine on linux now, see commit here: https://github.com/deltachat/deltachat-node/commit/f634f5cca4864ea53153579b17aea696dce24117

Next step is to try and build this for osx (and also simplify `scripts/travis-before-install`)
