### ISSUE TITLE
Test build on windows

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#9]

**Comment by ralphtheninja** [comment]
Believe it or not, I'm pondering buying a windows machine. Blasphemy, I know, but getting tired of not being able to fix windows stuff.

**Comment by homdx** [comment]
Builded binary deltachat-core need testing:
[deltachat/deltachat-core#306 (comment)](https://github.com/deltachat/deltachat-core/issues/306#issuecomment-461026117)
Possible problems: Windows does not support utf-8 coding, windows uses ansi encoding. (need fix).

**Comment by homdx** [comment]
You can build under Windows with my instruction:
https://github.com/deltachat/deltachat-desktop/issues/606#issuecomment-465064978
